spring:
  jpa:
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/ORCLCDB.localdomain
    username: lincoln
    password: lincoln

  flyway:
    enabled: true
    validate-on-migrate: true
    out-of-order: true
    baseline-on-migrate: true