CREATE SEQUENCE SEQ_CONTATO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1;
CREATE TABLE CONTATO (ID INTEGER NOT NULL, EMAIL VARCHAR(255) NOT NULL, NOME VARCHAR(255), TELEFONE VARCHAR(255) NOT NULL, FK_USUARIO INTEGER, PRIMARY KEY (ID));
CREATE TABLE USUARIO (ID INTEGER NOT NULL, CPF VARCHAR(255) NOT NULL, DATA_NASCIMENTO TIMESTAMP, NOME VARCHAR(255) NOT NULL, PRIMARY KEY (ID));
ALTER TABLE CONTATO ADD CONSTRAINT CONTATO_EMAIL_UNIQUE UNIQUE (EMAIL);
ALTER TABLE CONTATO ADD CONSTRAINT CONTATO_TELEFONE_UNIQUE UNIQUE (TELEFONE);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_CPF_UNIQUE UNIQUE (CPF);
ALTER TABLE CONTATO ADD CONSTRAINT FK_CONTATO_USUARIO FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO;